title: "250926 Theme"

baseurl: "/250926-theme"

copyright: "2021-2025 <a href=\"https://sidroberts.co.uk/\">Sid Roberts</a>"

gh_repository:      "SidRoberts/250926-theme"
gh_dir:             ""
gh_branch:          "main"
gh_edit_view_mode:  "edit"
